[package]
name = "web-api"
version = "0.1.0"
authors = ["Spxg <itsme@spxg.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.5"
diesel = "1.4"

[dependencies.rocket_contrib]
version = "0.4.5"
features = ["json", "diesel_mysql_pool"]

